///////////////////////////////////////////////////////////////////////////////
// ProgettoCClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ProgettoCClassFactory.h"
#include "ProgettoCServices.h"
#include "ProgettoCVersion.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CProgettoCClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_ProgettoC, CID_ProgettoCCModule1, SRVNAME_PROGETTOC "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CProgettoCClassFactory::CProgettoCClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_PROGETTOC));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ProgettoC));
#endif //defined(TCDBG_UNIT_VERSION)
}

