///////////////////////////////////////////////////////////////////////////////
// ProgettoCServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ProgettoC = 0x3F000000;
#define SRVNAME_PROGETTOC "ProgettoC"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ProgettoCCModule1 = {0x7e2844fb,0x6546,0x4906,{0xaf,0xfc,0xf2,0x72,0xa5,0x4c,0xe0,0x94}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
