<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{bab0ef4a-2e3e-4ede-a8f2-ff177030bc12}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	test	: DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[test:=test+1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>