<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{51e18e0a-bf97-43bb-bd25-74158815971f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ReadAnalogInput();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>