<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU" Id="{9f48191b-4191-4add-aa03-59f1ad082999}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION POU : DINT
VAR_INPUT
	a: DINT;
	b: DINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Somma := a + b;
]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="7" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>